import 'control_val.dart';

List val_pic_card_network = [
  "https://$address_ip/assets/assets/cards/dg_mc01sb_back.png",
  "https://$address_ip/assets/assets/cards/dg_mc01sb_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01go_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01go_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01ib_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01ib_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01mm_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01mm_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01rb_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01rb_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01re_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01re_front.png",
  "https://$address_ip/assets/assets/cards/dg_ec01sa_back.png",
  "https://$address_ip/assets/assets/cards/dg_ec01sa_front.png",
  "https://$address_ip/assets/assets/cards/dg_le01rd_back.png",
  "https://$address_ip/assets/assets/cards/dg_le01rd_front.png",
  "https://$address_ip/assets/assets/cards/dg_mc01sw_back.png",
  "https://$address_ip/assets/assets/cards/dg_mc01sw_front.png",
  "https://$address_ip/assets/assets/cards/1_gray.png",
];
List val_pic_image_network = [
  "https://$address_ip/assets/assets/images/1.gif",
  "https://$address_ip/assets/assets/images/2.jpg",
  "https://$address_ip/assets/assets/images/3.jpg",
  "https://$address_ip/assets/assets/images/4.jpg",
  "https://$address_ip/assets/assets/images/5.jpg",
  "https://$address_ip/assets/assets/images/6.png",
  "https://$address_ip/assets/assets/images/7.png",
  "https://$address_ip/assets/assets/images/8.png",
  "https://$address_ip/assets/assets/images/9.png",
  "https://$address_ip/assets/assets/images/10.png",
  "https://$address_ip/assets/assets/images/11.png",
  "https://$address_ip/assets/assets/images/12.png",
  "https://$address_ip/assets/assets/images/13.png",
  "https://$address_ip/assets/assets/images/14.png",
  "https://$address_ip/assets/assets/images/15.png",
  "https://$address_ip/assets/assets/images/16.png",
  "https://$address_ip/assets/assets/images/17.png",
  "https://$address_ip/assets/assets/images/18.png",
  "https://$address_ip/assets/assets/images/19.png",
  "https://$address_ip/assets/assets/images/20.png",
  "https://$address_ip/assets/assets/images/21.png",
  "https://$address_ip/assets/assets/images/22.png",
  "https://$address_ip/assets/assets/images/23.png",
  "https://$address_ip/assets/assets/images/24.png",
  "https://$address_ip/assets/assets/images/25.png",
  "https://$address_ip/assets/assets/images/26.png",
  "https://$address_ip/assets/assets/images/27.png",
  "https://$address_ip/assets/assets/images/28.png",
];
List val_pic_image_network2 = [
  "https://$address_ip/assets/assets/images/1.jpg",
  "https://$address_ip/assets/assets/images/2.jpg",
  "https://$address_ip/assets/assets/images/3.jpg",
  "https://$address_ip/assets/assets/images/4.jpg",
  "https://$address_ip/assets/assets/images/5.jpg",
  "https://$address_ip/assets/assets/images/6.png",
  "https://$address_ip/assets/assets/images/7.png",
  "https://$address_ip/assets/assets/images/8.png",
  "https://$address_ip/assets/assets/images/9.png",
  "https://$address_ip/assets/assets/images/10.png",
  "https://$address_ip/assets/assets/images/11.png",
  "https://$address_ip/assets/assets/images/12.png",
  "https://$address_ip/assets/assets/images/13.png",
  "https://$address_ip/assets/assets/images/14.png",
  "https://$address_ip/assets/assets/images/15.png",
  "https://$address_ip/assets/assets/images/16.png",
  "https://$address_ip/assets/assets/images/17.png",
  "https://$address_ip/assets/assets/images/18.png",
  "https://$address_ip/assets/assets/images/19.png",
  "https://$address_ip/assets/assets/images/20.png",
  "https://$address_ip/assets/assets/images/21.png",
  "https://$address_ip/assets/assets/images/22.png",
  "https://$address_ip/assets/assets/images/23.png",
  "https://$address_ip/assets/assets/images/24.png",
  "https://$address_ip/assets/assets/images/25.png",
  "https://$address_ip/assets/assets/images/26.png",
];
List val_pic_png_network = [
  "https://$address_ip/assets/assets/png/1.png",
  "https://$address_ip/assets/assets/png/2.png",
  "https://$address_ip/assets/assets/png/3.png",
  "https://$address_ip/assets/assets/png/4.png",
  "https://$address_ip/assets/assets/png/5.png",
  "https://$address_ip/assets/assets/png/6.png",
  "https://$address_ip/assets/assets/png/7.png",
  "https://$address_ip/assets/assets/png/8.png",
  "https://$address_ip/assets/assets/png/9.png",
  "https://$address_ip/assets/assets/png/10.png",
  "https://$address_ip/assets/assets/png/11.png",
  "https://$address_ip/assets/assets/png/12.png",
  "https://$address_ip/assets/assets/png/13.png",
  "https://$address_ip/assets/assets/png/14.png",
  "https://$address_ip/assets/assets/png/15.png",
  "https://$address_ip/assets/assets/png/16.png", //15
  "https://$address_ip/assets/assets/png/delete.png",
  "https://$address_ip/assets/assets/png/shop.png",
  "https://$address_ip/assets/assets/png/activ.png",
  "https://$address_ip/assets/assets/png/qr.png", //19
  "https://$address_ip/assets/assets/png/20.png",
  "https://$address_ip/assets/assets/png/21.png",

  "https://$address_ip/assets/assets/png/empety.jpg",
  "https://$address_ip/assets/assets/png/new1.png",
  "https://$address_ip/assets/assets/png/new2.png",
  "https://$address_ip/assets/assets/png/stand.png",
];
List val_video_network = [
  "https://$address_ip/assets/assets/png/black_video.mp4",
];
List val_pic_share = [
  "https://$address_ip/digic_pic/user/share/DIGICA_icons/Gmail.png",
  "https://$address_ip/digic_pic/user/share/DIGICA_icons/Facebook.png",
  "https://$address_ip/digic_pic/user/share/DIGICA_icons/Apple.png",
  "https://$address_ip/assets/assets/png/4.png",
  "https://$address_ip/assets/assets/png/5.png",
  "https://$address_ip/assets/assets/png/6.png",
  "https://$address_ip/assets/assets/png/7.png",
  "https://$address_ip/assets/assets/png/8.png",
  "https://$address_ip/assets/assets/png/9.png",
  "https://$address_ip/assets/assets/png/10.png",
  "https://$address_ip/assets/assets/png/11.png",
  "https://$address_ip/assets/assets/png/12.png",
  "https://$address_ip/assets/assets/png/13.png",
  "https://$address_ip/assets/assets/png/14.png",
  "https://$address_ip/assets/assets/png/15.png",
  "https://$address_ip/assets/assets/png/16.png", //15
  "https://$address_ip/assets/assets/png/delete.png",
  "https://$address_ip/assets/assets/png/shop.png",
  "https://$address_ip/assets/assets/png/activ.png",
  "https://$address_ip/assets/assets/png/qr.png", //19
  "https://$address_ip/assets/assets/png/20.png",
  "https://$address_ip/assets/assets/png/21.png",

  "https://$address_ip/assets/assets/png/empety.jpg",
  "https://$address_ip/assets/assets/png/new1.png",
  "https://$address_ip/assets/assets/png/new2.png",
  "https://$address_ip/assets/assets/png/stand.png",
];
